package com.example.login.util

object Constants {



    const val INDIVIDUAL_CUSTOMER_OR_TC_ID__MIN_LENGTH = 10
    const val INDIVIDUAL_CUSTOMER_OR_TC_ID__MAX_LENGTH = 11
    const val INDIVIDUAL_PASSWORD_MIN_LENGTH = 6
    const val INDIVIDUAL_PASSWORD_MAX_LENGTH = 8



    const val COMMERCIAL_CUSTOMER_NUMBER_MIN_LENGTH = 11
    const val COMMERCIAL_CUSTOMER_NUMBER_MAX_LENGTH = 12
    const val COMMERCIAL_USER_CODE_MIN_LENGTH = 10
    const val COMMERCIAL_USER_CODE_MAX_LENGTH = 11
    const val COMMERCIAL_PASSWORD_MIN_LENGTH = 6
    const val COMMERCIAL_PASSWORD_MAX_LENGTH = 8

}